package com.example.systemious.utils

object Constants{
    const val SERVICE_INFO_NOTIFICATION_ID = 15671
    const val SERVICE_INFO_NOTIFICATION_CHANNEL_ID = "SYSTEMIOUS_SERVICE_INFO_NOTIFICATION_CHANNEL_ID"
    const val SERVICE_INFO_NOTIFICATION_CHANNEL_NAME = "SYSTEMIOUS_SERVICE_INFO_NOTIFICATION_CHANNEL_NAME"
}